---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "inst/images/"
)
```

# streamnet

Morphology analysis of stream networks 

## Installation

You can install streamnet from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("jsta/streamnet")
```

## Usage

<details>
 <summary>Generate test stream network</summary>

```{r test_dataset}
library(sf)
library(ggplot2)
library(nhdR)
library(streamnet)

# Generate test dataset
bbox <- data.frame(xmin = -73.33838, ymin = 41.35841,
                   xmax = -73.14540, ymax = 41.48593)
b0 <- sf::st_sfc(sf::st_polygon(list(rbind(
    c(bbox$xmin, bbox$ymin),
    c(bbox$xmax, bbox$ymin),
    c(bbox$xmax, bbox$ymax),
    c(bbox$xmin, bbox$ymax),
    c(bbox$xmin, bbox$ymin)))))
sf::st_crs(b0) <- 4326
b0 <- st_transform(b0, sf::st_crs(nhdR::vpu_shp))

outlet_reach <- terminal_reaches(
                 lon = st_coordinates(st_centroid(b0))[1], 
                 lat = st_coordinates(st_centroid(b0))[2])
outlet_point <- st_cast(st_line_sample(outlet_reach, sample = 1), "POINT")

nhd <- nhd_plus_query(poly = b0, dsn = c("NHDFlowLine"))$sp$NHDFlowLine
```
</details>

<details>
 <summary>Calculate stream order</summary>
 
```{r grass_stream-order}
Sys.setenv(GRASS_VERBOSE = -1) # suppress grass messages

res <- stream_order(lines = nhd, outlet = outlet_point)

coords <- st_coordinates(st_transform(outlet_point, 4326))
poly   <- nhd_plus_query(coords[1], coords[2], 
                        dsn = "NHDWaterbody")$sp$NHDWaterbody

ggplot() + 
  geom_sf(data = poly, color = "white") +
  geom_sf(data = res, aes(color = as.factor(strahler)))
```
</details>

<details>
  <summary>Calculate average link length</summary>

```{r }  
avg_link_length(lines = nhd, outlet_reach = outlet_reach)
```
</details>

<details>
  <summary>Calculate distance to closest upstream lake</summary>
  
```{r }
1 + 1
```
</details>
