# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' gauss_ran
#'
#' @export
gauss_ran <- function() {
    .Call('_streamnet_gauss_ran', PACKAGE = 'streamnet')
}

#' timesTwo
#'
#' @param x int
#' @export
timesTwo <- function(x) {
    .Call('_streamnet_timesTwo', PACKAGE = 'streamnet', x)
}

